let companyConfig = {
    "system":{
        "software":{
            "version":"0.1",
            "version-name":'SGA deploy Test',
            "last-update":"10/01/2026",
            "next-maintenance":"01/02/2026",
            "under-maintenance":false,
        },
        "locks":{
            "update":false,
            "free-use":false,
            "license":false,
            "maintenance":false
        }
    },
    "billing":{
        "type":"monthly",
        "charge":"auto",
        "discounts":[],
        "name":"",
        "direction":"",
        "mail":"",
        "phone":""
    },
    "access":{
        "suspended":false,
        "modules":{
            "management":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "inventory":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "process":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "sga-home":{
                "use":true,
                "instance":"full",
                "expires":"---"
            },
            "facturation":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "contability":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "treasury":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "ctools":{
                "use":false,
                "instance":"alpha",
                "expires":"---"
            },
            "certicloud":{
                "use":false,
                "instance":"alpha",
                "expires":"---"
            },
        },
        "services":{
            "sga":{
                "messaging":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
                "AI":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
                "mail":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
                "calendar":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
                "cloud-storage":{
                    "use":true,
                    "instance":"full",
                    "expires":"---",
                    "limint":'----'
                },
                "advertising":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
                "analytics":{
                    "use":true,
                    "instance":"full",
                    "expires":"---"
                },
            },
            "personalized":{}
        }
    },
    "features":{
        "stores":{
            "multiple":true,
            "limit":"full"
        },
        "cellars":{
            "multiple":true,
            "limit":"full"
        },
        "users":{
            "multiple":true,
            "limit":"full"
        },
        "thirdParties":{
            "multiple":true,
            "limit":"full"
        },
        "products":{
            "multiple":true,
            "limit":"full"
        }, 
        "categories":{
            "multiple":true,
            "limit":"full"
        },
        "prices-lisy":{
            "multiple":true,
            "limit":"full"
        }
    }
}
