let userConfig = {
    "account":{
        "recordSesion":false,
        "status":"active",
        "locked":false
    },
    "system":{
        "language":"es",
        "region":"Colombia",
        "hour":"local"
    },
    "security":{
        "authentication":{
            "logIn":{
                "allways":false,
                "backUpMethod":false,
                "keyWord":""
            },
            "logOut":{
                "never":false,
                "frecuncy":"dayly"
            },
            "two-steps-verification":{
                "enable":false,
                "default-method":"email-code",
                "backup-method":"tel-code"
            },
            "biometricData":{
                "enable":false,
                "requirePin":false
            },
            "devices":{
                "allow-multiple":true,
                "limit":3
            }
        }
    },
    "access":{
        "suspended":false,
        "information":{
            "utilities":{
                "overAll":true,
                "thirdParties":true,
                "onlyOwnInformation":false
            }
        },
        "stores":{
            "overAll":false,
            "enabled":[6]
        },
        "cellars":{
            "overAll":false,
            "enabled":[]
        },
        "modules":{
            "management":{
                "use":false,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "inventory":{
                "use":false,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "process":{
                "use":false,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "sga-home":{
                "use":false,
                "instance":"full",
                "expires":"never"
            },
            "facturation":{
                "use":false,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "contability":{
                "use":false,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "treasury":{
                "use":true,
                "instance":"full",
                "expires":"10/01/2026"
            },
            "ctools":{
                "use":false,
                "instance":"alpha",
                "expires":"never"
            },
            "certicloud":{
                "use":false,
                "instance":"alpha",
                "expires":"never"
            }
        },
        "sections":{
            "new":{
                "overAll":true
            },
            "myBussines":{
                "overAll":false
            },
            "controlPanel":{
                "overAll":false
            },
            "modules":{
                "overAll":false
            },
            "services":{
                "overAll":false
            },
            "billing":{
                "overAll":false
            },
            "thirdparties":{
                "overAll":true,
                "can_create":false,
                "can_delete":false,
                "can_edit":false
            },
            "users":{
                "overAll":false,
                "can_create":false,
                "can_delete":false,
                "can_edit":false
            },
            "reports":{
                "overAll":true,
                "documents":{
                    "overAll":true,
                    "clientOrders":true,
                    "productionOrders":true,
                    "purchase":true,
                    "consume":true,
                    "sells":true,
                    "transactions":true,
                    "reportedDocs":true,
                    "clientOrdersVolume":true
                },
                "company":{
                    "operative-cost":true,
                    "testBalane":true,
                    "usersProductivity":true,
                    "processEfficiency":true,
                    "executionState":true
                }
            },
            "analytics":{
                "overAll":false
            },
            "concepts":{
                "overAll":false
            },
            "accounts":{
                "overAll":false
            },
            "search":{
                "overAll":false
            },
            "stores":{
                "overAll":false
            },
            "products":{
                "overAll":false
            },
            "categories":{
                "overAll":false
            },
            "pricesList":{
                "overAll":false
            },
            "movements":{
                "overAll":false
            },
            "newDocument":{
                "overAll":true,
                "can_create":true,
                "can_delete":false,
                "can_edit":false,
                "can_comment":false,
                "can_report":false,
                "allowedDocuments":[]
            },
            "settings":{
                "overAll":true
            },
            "tutorials":{
                "overAll":true
            },
            "help":{
                "overAll":true
            }
        },
        "services":{
            "sga":{
                "messaging":{
                    "use":true,
                    "instance":"full",
                    "expires":"never"
                },
                "AI":{
                    "use":true,
                    "instance":"full",
                    "expires":"never"
                },
                "mail":{
                    "use":false,
                    "instance":"full",
                    "expires":"never"
                },
                "calendar":{
                    "use":false,
                    "instance":"full",
                    "expires":"never"
                },
                "cloud-storage":{
                    "use":true,
                    "instance":"full",
                    "expires":"never",
                    "limint":"never-"
                },
                "advertising":{
                    "use":false,
                    "instance":"full",
                    "expires":"never"
                },
                "analytics":{
                    "use":false,
                    "instance":"full",
                    "expires":"never"
                }
            },
            "personalized":{}
        }
    },
    "notifications":{
        "mode":"float",
        "focus":"disabled",
        "sound&efects":false,
        "programedResume":"disabled",
        "groupNotifications":false
    },
    "styles":{
        "theme":{
            "default":"light",
            "ligthImg":"https://i.pinimg.com/1200x/23/5f/8d/235f8df39cf98153029b9cc09495f390.jpg",
            "darkImg":"https://i.pinimg.com/1200x/80/d1/bd/80d1bd8f8c9777a8ff1a8b4ed534418e.jpg",
            "colorPalete":"default"
        },
        "typography":{
            "style":"normal",
            "font-size":"normal",
            "line-height":"auto",
            "line-width":"auto",
            "contrast":"normal"
        },
        "iconography":{
            "show-imgs":true,
            "only-icons":false,
            "icons-size":"normal"
        },
        "dashboard":{
            "distribution":"normal",
            "editable":false
        },
        "widgets":{
            "show-widgets":true,
            "only-escentials":false,
            "editable":false
        },
        "tables":{
            "editable":false
        },
        "animations":{
            "active":true,
            "only-escentials":false,
            "speed":"normal"
        }
    },
    "meta": {
        "version": "1.0",
        "updatedAt": "2026-01-10"
        }
}