-- Migration: 0024_create_orders_delegation
-- Fecha: 2026-09-11
-- Aditiva. Aplicar con psql --single-transaction, después de respaldo.
-- Requiere el tipo documental existente 'ThirdParty Delegation'.
-- Rollback: 0024_create_orders_delegation.rollback.sql (solo sin datos).

CREATE TABLE IF NOT EXISTS "Process".orders_delegation_config (
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    parent_process_id bigint NOT NULL REFERENCES "Process".processes(id),
    assignment_step_id bigint NOT NULL REFERENCES "Process".process_steps(id),
    production_step_id bigint NOT NULL REFERENCES "Process".process_steps(id),
    child_process_id bigint NOT NULL REFERENCES "Process".processes(id),
    child_initial_step_id bigint NOT NULL REFERENCES "Process".process_steps(id),
    document_type public.document_types NOT NULL DEFAULT 'ThirdParty Delegation',
    PRIMARY KEY (company_id, parent_process_id),
    CHECK (assignment_step_id <> production_step_id),
    CHECK (parent_process_id <> child_process_id)
);

CREATE TABLE IF NOT EXISTS "Process".orders_delegation_requests (
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    request_id uuid NOT NULL,
    payload_hash text NOT NULL,
    response jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (company_id, request_id)
);

CREATE TABLE IF NOT EXISTS "Process"."ordersDelegation" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    service_movement_id bigint NOT NULL REFERENCES "Inventory".services_movement(id) ON DELETE RESTRICT,
    delegation_document_id bigint NOT NULL REFERENCES "Ecosystem".documents(id) ON DELETE RESTRICT,
    "thirdParty_id" bigint NOT NULL REFERENCES "Ecosystem".thirdparties(id) ON DELETE RESTRICT,
    asignation_note text NOT NULL DEFAULT '',
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','superseded','cancelled')),
    created_by bigint NOT NULL REFERENCES "Ecosystem".users(user_id),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS orders_delegation_active_item
    ON "Process"."ordersDelegation" (company_id, service_movement_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS orders_delegation_document
    ON "Process"."ordersDelegation" (company_id, delegation_document_id);
CREATE INDEX IF NOT EXISTS process_instance_parent_step
    ON "Process".process_instance (company_id, parent_id, parent_step);

-- Parametrización existente verificada: compañía 7, OP y PP.
-- Resolver IDs por configuración; no sobrescribir una configuración ya existente.
INSERT INTO "Process".orders_delegation_config (
    company_id, parent_process_id, assignment_step_id, production_step_id,
    child_process_id, child_initial_step_id
)
SELECT parent.company_id, parent.id, assignment.id, production.id, child.id, initial.id
FROM "Process".processes parent
JOIN "Process".process_steps assignment ON assignment.process_id = parent.id
    AND assignment.company_id = parent.company_id AND assignment.name = 'Asignación Proveedores'
JOIN "Process".process_steps production ON production.process_id = parent.id
    AND production.company_id = parent.company_id AND production.name = 'En producción'
JOIN "Process".processes child ON child.company_id = parent.company_id AND child.code = 'PP'
JOIN "Process".process_steps initial ON initial.process_id = child.id
    AND initial.company_id = child.company_id AND initial."order" = 0
WHERE parent.company_id = 7 AND parent.code = 'OP'
ON CONFLICT (company_id, parent_process_id) DO NOTHING;

INSERT INTO public.schema_migrations(filename)
VALUES ('0024_create_orders_delegation.sql') ON CONFLICT DO NOTHING;
