-- Migration: 0029_create_accounting_adjustment_templates
-- Fecha:     2026-09-19
-- Regla:     aditiva; no modifica comprobantes ni movimientos existentes.
-- Rollback:  no ejecutar en producción mientras existan plantillas que dependan de esta tabla.

BEGIN;
SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '30s';

CREATE TABLE IF NOT EXISTS "Ecosystem".accounting_adjustment_templates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL,
    name varchar(120) NOT NULL,
    lines jsonb NOT NULL,
    description text NOT NULL DEFAULT '',
    created_by bigint NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT accounting_adjustment_templates_company_name_key UNIQUE (company_id, name),
    CONSTRAINT accounting_adjustment_templates_lines_array CHECK (jsonb_typeof(lines) = 'array')
);

CREATE INDEX IF NOT EXISTS accounting_adjustment_templates_company_idx
    ON "Ecosystem".accounting_adjustment_templates (company_id, name);

INSERT INTO public.schema_migrations (filename)
VALUES ('0029_create_accounting_adjustment_templates.sql') ON CONFLICT (filename) DO NOTHING;
COMMIT;
