-- Migration: 0030_create_nexo_delivery_orders
-- Fecha:     2026-09-23
-- Regla:     solo aditiva; las órdenes emitidas se conservan como trazabilidad.
-- Rollback:  no aplicar con datos. Revocar acceso a la funcionalidad si fuera necesario.

BEGIN;

CREATE TABLE IF NOT EXISTS "Process".delivery_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    sequence_number bigint NOT NULL,
    order_number text NOT NULL,
    supplier_id bigint NOT NULL REFERENCES "Ecosystem".thirdparties(id) ON DELETE RESTRICT,
    status text NOT NULL DEFAULT 'draft'
        CHECK (status IN ('draft', 'issued', 'delivered', 'closed', 'cancelled')),
    issued_on date NOT NULL,
    scheduled_at timestamptz NOT NULL,
    pickup_location text NOT NULL DEFAULT '',
    authorized_name text NOT NULL DEFAULT '',
    authorized_identification text NOT NULL DEFAULT '',
    authorized_phone text NOT NULL DEFAULT '',
    vehicle_type text NOT NULL DEFAULT '',
    vehicle_plate text NOT NULL DEFAULT '',
    driver_name text NOT NULL DEFAULT '',
    observations text NOT NULL DEFAULT '',
    created_by bigint NOT NULL REFERENCES "Ecosystem".users(user_id),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (company_id, sequence_number),
    UNIQUE (company_id, order_number)
);

CREATE TABLE IF NOT EXISTS "Process".delivery_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_order_id bigint NOT NULL REFERENCES "Process".delivery_orders(id) ON DELETE RESTRICT,
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    service_movement_id bigint NOT NULL REFERENCES "Inventory".services_movement(id) ON DELETE RESTRICT,
    client_order_id bigint NOT NULL REFERENCES "Ecosystem".documents(id) ON DELETE RESTRICT,
    delegation_document_id bigint NOT NULL REFERENCES "Ecosystem".documents(id) ON DELETE RESTRICT,
    process_instance_id bigint NULL REFERENCES "Process".process_instance(id) ON DELETE RESTRICT,
    product_type text NOT NULL DEFAULT 'OTRO',
    quantity numeric(18,4) NOT NULL CHECK (quantity > 0),
    description text NOT NULL,
    store_reference text NOT NULL DEFAULT '',
    width text NOT NULL DEFAULT '',
    height text NOT NULL DEFAULT '',
    city text NOT NULL DEFAULT '',
    observations text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (delivery_order_id, service_movement_id)
);

CREATE TABLE IF NOT EXISTS "Process".delivery_order_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_order_id bigint NOT NULL REFERENCES "Process".delivery_orders(id) ON DELETE RESTRICT,
    company_id bigint NOT NULL REFERENCES "Ecosystem".companies(company_id),
    user_id bigint NOT NULL REFERENCES "Ecosystem".users(user_id),
    action text NOT NULL,
    detail text NOT NULL DEFAULT '',
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS delivery_orders_company_status_scheduled_idx
    ON "Process".delivery_orders (company_id, status, scheduled_at DESC);
CREATE INDEX IF NOT EXISTS delivery_order_items_source_idx
    ON "Process".delivery_order_items (company_id, service_movement_id);
CREATE INDEX IF NOT EXISTS delivery_order_events_order_idx
    ON "Process".delivery_order_events (delivery_order_id, created_at DESC);

INSERT INTO public.schema_migrations(filename)
VALUES ('0030_create_nexo_delivery_orders.sql') ON CONFLICT DO NOTHING;

COMMIT;
