-- Esquema mínimo de prueba basado en el catálogo verificado el 2026-09-11.
CREATE SCHEMA "Ecosystem";
CREATE SCHEMA "Inventory";
CREATE SCHEMA "Process";
CREATE TYPE public.document_types AS ENUM ('Client Order','ThirdParty Delegation');
CREATE TYPE public.comercial_state AS ENUM ('active','cancelled','disabled');
CREATE TABLE public.schema_migrations(filename text PRIMARY KEY);
CREATE TABLE "Ecosystem".companies(company_id bigint PRIMARY KEY);
CREATE TABLE "Ecosystem".users(user_id bigint PRIMARY KEY,company_id bigint);
CREATE TABLE "Ecosystem".thirdparties(id bigint PRIMARY KEY,company_id bigint,names text,type text);
CREATE TABLE "Ecosystem".company_settings(company_id bigint PRIMARY KEY,time_zone text);
CREATE TABLE "Process".processes(id bigint PRIMARY KEY,company_id bigint,code text,status public.comercial_state DEFAULT 'active');
CREATE TABLE "Process".process_steps(id bigint PRIMARY KEY,company_id bigint,process_id bigint REFERENCES "Process".processes(id),name text,"order" bigint,required_roll bigint[],end_process boolean DEFAULT false);
CREATE TABLE "Process".process_instance(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,company_id bigint,process_id bigint,step_id bigint,
    status public.comercial_state,parent_id bigint,parent_step bigint,start_date timestamp,"delivery_date" timestamp,
    "thirdParty_id" bigint,responsable bigint,created_at timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at timestamp DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),"ownSerial" bigint GENERATED BY DEFAULT AS IDENTITY
);
CREATE TABLE "Process".process_historial(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,company_id bigint,instance_id bigint REFERENCES "Process".process_instance(id),previous_step bigint,next_step bigint,user_id bigint,created_at timestamp,description text);
CREATE TABLE "Ecosystem".documents(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,company_id bigint,store_id bigint,"thirdParty_id" bigint,
    document_type public.document_types,status public.comercial_state,"subTotal" numeric,total numeric,created_by bigint,
    description text,attached text,instance_id bigint,step_instance bigint,"ownSerial" bigint GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP,updated_at timestamptz DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Ecosystem".documents_group(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,main_doc_id bigint REFERENCES "Ecosystem".documents(id),doc_id bigint REFERENCES "Ecosystem".documents(id));
CREATE TABLE "Ecosystem".docs_instances(doc_id bigint REFERENCES "Ecosystem".documents(id),instance_id bigint REFERENCES "Process".process_instance(id),step_instance bigint,UNIQUE(doc_id,instance_id));
CREATE TABLE "Inventory".services_movement(id bigint PRIMARY KEY,company_id bigint,doc_id bigint REFERENCES "Ecosystem".documents(id),service_id bigint,units bigint);
INSERT INTO "Ecosystem".companies VALUES(7),(8);
INSERT INTO "Ecosystem".users VALUES(83,7);
INSERT INTO "Ecosystem".thirdparties VALUES(212,7,'José','supplier'),(213,7,'Juan','both'),(214,8,'Otra compañía','supplier'),(215,7,'Cliente','client');
INSERT INTO "Ecosystem".company_settings VALUES(7,'America/Bogota'),(8,'America/New_York');
INSERT INTO "Process".processes VALUES(9,7,'OP','active'),(10,7,'PP','active');
INSERT INTO "Process".process_steps VALUES
    (70,7,9,'Asignación Proveedores',2,ARRAY[30],false),
    (71,7,9,'En producción',3,ARRAY[30],false),
    (72,7,9,'Terminando',4,ARRAY[30],false),
    (76,7,10,'Asignado',0,ARRAY[30],false),
    (80,7,10,'Entregado',4,ARRAY[30],true);
